name: Setup Node app
description: Install Node dependencies with npm cache

runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: npm
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      shell: bash
      run: npm ci
